### ISSUE TITLE
Error registering Citation Key column on startup after update to v7.0.6 on Zotero 7.0.7

### ISSUE THREAD

**Issue by HarrisonGrodin** [retorquere/zotero-better-bibtex#3187]
### Debug log ID

VD9368Z5-refs-euc/7.0.6

### What happened?

Upon starting Zotero, I get the following error message as a popup:
```
TypeError: Zotero.ItemTreeManager.registerColumn is not a function
startup@jar:file:///home/user/.zotero/zotero/31jw53e0.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js:135474:62
run@jar:file:///home/user/.zotero/zotero/31jw53e0.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js:9112:32
```

**Comment by retorquere** [comment]
You need to upgrade Zotero, you are still on 7.0.7, Zotero is at 7.0.15

**Comment by HarrisonGrodin** [comment]
Indeed, that solved it. Thank you! (And, thanks for `zotero-deb`!)
